import {
  Cpu,
  Globe,
  Smartphone,
  BrainCircuit,
  Radio,
  Bot,
  Cloud,
  ShieldCheck,
  Network,
  PenTool,
  Workflow,
  Lightbulb,
  Database,
  Server,
  Code2,
  LineChart,
  Layers,
  Rocket,
  Award,
  Users,
  Wrench,
  GraduationCap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  cpu: Cpu,
  globe: Globe,
  smartphone: Smartphone,
  ai: BrainCircuit,
  iot: Radio,
  robotics: Bot,
  cloud: Cloud,
  security: ShieldCheck,
  network: Network,
  design: PenTool,
  automation: Workflow,
  consulting: Lightbulb,
  database: Database,
  server: Server,
  code: Code2,
  analytics: LineChart,
  layers: Layers,
  rocket: Rocket,
  award: Award,
  team: Users,
  tools: Wrench,
  education: GraduationCap,
};

export function getIcon(key: string | null | undefined): LucideIcon {
  return (key && ICONS[key]) || Cpu;
}
